### ISSUE TITLE
Add instructions

### ISSUE THREAD

**Issue by zenorocha** [dracula/xresources#3]
Hey @Aszarsha, could you share the instructions to activate this theme? I need that in order to create a page on draculatheme.com ;)

**Comment by Aszarsha** [comment]
@zenorocha I updated the README.md with the very simple instructions. :-)
Do you need anything else?

**Comment by zenorocha** [comment]
Thanks! You can send a pull request to https://github.com/dracula/dracula.github.io to speed up the process of adding it ;)
