### ISSUE TITLE
color4 is incorrect

### ISSUE THREAD

**Issue by dsifford** [dracula/xresources#4]
color4 should be `#bd93f9`. Currently it is identical to color12 `#CAA9FA`.

**Comment by Aszarsha** [comment]
Thank you @dsifford for catching this! :-)

**Comment by ankkerbintang** [comment]
Git clone https://support.hp.com/us-en?openCLC=true

**Comment by Ataarya** [comment]
ممنون که هستین و خدماتی که ارائه‌ میدین بی نظیر هستن .
موفق باشین .🙏🙏🙏
